# Generated by Django 5.1.2 on 2025-03-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uagain', '0002_productos_creador_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
