# Generated by Django 5.1.2 on 2025-05-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uagain', '0004_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
