# Generated by Django 5.1.2 on 2025-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uagain', '0005_alter_productos_descripcion_alter_productos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='productos/default.webp', upload_to='productos/'),
        ),
    ]
