name: Django CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run collectstatic
      env:
        DJANGO_SETTINGS_MODULE: tesis.settings  # ajusta si usas otro settings
        SECRET_KEY: dummy  # necesario si tu settings.py lo exige
      run: |
        python manage.py collectstatic --noinput

    - name: Zip artifact for deployment
      run: |
        zip -r app.zip . -x "*.git*" "*/__pycache__/*" "*.github*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AgainU'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: app.zip